name: untitled1
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.5
  sqlite3: ^2.7.6
  path: ^1.9.1
  intl: ^0.20.2
  logging: ^1.3.0

dev_dependencies:
  http: ^1.4.0
  lints: ^6.0.0
  test: ^1.26.2
  freezed: ^3.0.6
  build_runner: ^2.5.3
  json_serializable: ^6.9.5

